export const navItems = [
    {
        id: 0,
        text: "About",
        icon: "mdi-social-person",
        color: "teal-text",
        redirectTo: "#about",
    },
    {
        id: 1,
        text: "Experience",
        icon: "mdi-action-trending-up",
        color: "cyan-text",
        redirectTo: "#experience",
    },
    {
        id: 2,
        text: "Projects",
        icon: "mdi-av-web",
        color: "indigo-text",
        redirectTo: "#projects",
    },
    {
        id: 3,
        text: "Skills",
        icon: "mdi-av-equalizer",
        color: "purple-text",
        redirectTo: "#skills",
    },
    {
        id: 4,
        text: "Awards",
        icon: "mdi-action-grade",
        color: "red-text",
        redirectTo: "#awards",
    },
    {
        id: 5,
        text: "Education",
        icon: "mdi-social-school",
        color: "orange-text",
        redirectTo: "#education",
    },
    {
        id: 6,
        text: "Contact",
        icon: "mdi-content-mail",
        color: "brown-text",
        redirectTo: "#contact",
    },
    {
        id: 7,
        text: "Resume",
        icon: "mdi-action-description",
        color: "grey-text",
        redirectTo: "Nishant_Nair_Resume6yrs.pdf",
        redirectToNewTab: true,
    },
];
